/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor_de_un_boton_otro;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class conversor_de_un_boton extends javax.swing.JFrame {

    /**
     * Creates new form conversor_de_un_boton
     */
    public conversor_de_un_boton() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        getContentPane().setBackground(Color.magenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conversorLabel = new javax.swing.JLabel();
        centimetrosLabel = new javax.swing.JLabel();
        pulgadasLabel = new javax.swing.JLabel();
        centimetrosTextField = new javax.swing.JTextField();
        pulgadasTextField = new javax.swing.JTextField();
        convertirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conversorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        conversorLabel.setText("CONVERSOR CENTÍMETROS-PULGADAS");

        centimetrosLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        centimetrosLabel.setText("Centímetros");

        pulgadasLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pulgadasLabel.setText("Pulgadas");

        centimetrosTextField.setBackground(new java.awt.Color(255, 255, 102));
        centimetrosTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                centimetrosTextFieldFocusLost(evt);
            }
        });

        pulgadasTextField.setBackground(new java.awt.Color(255, 255, 102));
        pulgadasTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pulgadasTextFieldFocusLost(evt);
            }
        });

        convertirButton.setBackground(new java.awt.Color(204, 153, 0));
        convertirButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        convertirButton.setText("Convertir");
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(centimetrosLabel)
                    .addComponent(pulgadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(centimetrosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulgadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(convertirButton)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(conversorLabel)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(conversorLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(centimetrosLabel)
                            .addComponent(centimetrosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulgadasLabel)
                            .addComponent(pulgadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(convertirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        // TODO add your handling code here:
        if (bandera == 1)
        {
            String centimetrosString=centimetrosTextField.getText();
        
            if(centimetrosString.isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Debe ingresar un número en el campo centímetros","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                return;
            }
            double centimetros;
            try
            {
                centimetros=Double.valueOf(centimetrosString);
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "El valor ingresado \""+centimetrosString+"\" no conforma un número", "ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            double pulgadas=centimetros/2.54;
            String pulgadasString=String.format("%.2f",pulgadas);
            pulgadasString=pulgadasString.replace(',','.');
            pulgadasTextField.setText(pulgadasString);
        }
        
        if (bandera == -1)
        {
            String pulgadasString=pulgadasTextField.getText();
        if(pulgadasString.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Debe ingresar un número en el campo pulgadas","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            return;
        }
        double pulgadas;
        try
        {
            pulgadas=Double.valueOf(pulgadasString);
        }
        catch(NumberFormatException ex)
        {
             JOptionPane.showMessageDialog(this,"El valor ingresado \""+pulgadasString+"\" no conforma un número","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
        }
        double centimetros=pulgadas*2.54;
        String centimetrosString=String.format("%.2f",centimetros);
        centimetrosString=centimetrosString.replace(',','.');
        centimetrosTextField.setText(centimetrosString);
        }
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void centimetrosTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_centimetrosTextFieldFocusLost
        // TODO add your handling code here:
        bandera=1;
    }//GEN-LAST:event_centimetrosTextFieldFocusLost

    private void pulgadasTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pulgadasTextFieldFocusLost
        // TODO add your handling code here:
        bandera=-1;
    }//GEN-LAST:event_pulgadasTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversor_de_un_boton().setVisible(true);
            }
        });
    }

    private int bandera;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel centimetrosLabel;
    private javax.swing.JTextField centimetrosTextField;
    private javax.swing.JLabel conversorLabel;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel pulgadasLabel;
    private javax.swing.JTextField pulgadasTextField;
    // End of variables declaration//GEN-END:variables
}
